$(document).ready(function(){
    $("#Open").click(function(){
      $("#menu").slideToggle("slow");
      $("#Close").show();
      $("#Open").hide();
      $("#ul_menu").show("slow")
    });
    $("#Close").click(function(){
      $("#menu").slideUp("slow");
      $("#Open").show();  
      $("#ul_menu").slideUp()  
    });
  });